load("@envoy_api//bazel:api_build_system.bzl", "api_proto_library_internal")

licenses(["notice"])

api_proto_library_internal(
    name = "memcached_proxy",
    srcs = ["memcached_proxy.proto"],
    deps = [],
)
